# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
# Serves board A's clock, which systemd-timesyncd keeps in sync with the Mac backend; chronyd runs
# with -x and never changes it. Unlike ntpd it answers as synchronized right after a (re)start,
# and stratum 2 or better is required by the MXChip's SNTP client.

local stratum 1
allow all
cmdport 0
# /var/run/chrony is not writable without DAC_OVERRIDE
pidfile /tmp/chronyd.pid
