/********************************************************************************
 * SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

 /*
 * AI Disclosure: This file was largely AI-generated by Claude Code (Opus 5.5).
 * The AI-generated portions may be considered public domain (CC0-1.0)
 * and not subject to the project's licence. The human contributor has
 * reviewed and verified that the code is correct.
 */

use std::sync::Arc;

use clap::Parser;
use common::AUDIENCE_SOVD_CDA;
use common::powertrain::{AUDIENCE_POWERTRAIN_MODE_CONTROL, ModeMessage};
use log::{debug, info, warn};
use regorus::CompiledPolicy;
use reqwest::Url;
use spiffe::{JwtSvid, WorkloadApiClient};
use up_rust::UAttributes;
use up_rust::communication::{
    InMemoryRpcServer, RequestHandler, RpcServer, ServiceInvocationError, UPayload,
};

use crate::cli::Cli;

mod cli;
// AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
mod status;

async fn get_rpc_server(cli: cli::Cli) -> Result<InMemoryRpcServer, Box<dyn std::error::Error>> {
    let uri_provider = cli.get_local_uri_provider()?;
    let transport = cli.get_transport().await?;
    Ok(InMemoryRpcServer::new(transport, uri_provider))
}

/// Regorous policies can return `Undefined` rather than `false`. A Rego rule that
/// does not match evaluates to `Undefined` (not `false`), preferred behavior is that anything
/// other than `true` is denied. Best practice would be to set up rego policy with 
/// `default allow := false` to ensure a fail-closed behavior. But to be extra cautious, the
/// `is_authorized` function explicitly checks for `true`.
/// In practice a separate function may not be needed, but for the sake of this blueprint 
/// and highlighting this to the user, this function is included.
fn is_authorized(decision: &regorus::Value) -> bool {
    matches!(decision, regorus::Value::Bool(true))
}

// { "data": { "Mode": "Performance" } }
#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub(crate) struct Root {
    data: ModeMessage,
}

// AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
// Safety net so that a lock is not held forever if releasing it fails.
const SOVD_LOCK_EXPIRATION_SECS: u64 = 10;

#[derive(Debug, serde::Deserialize)]
struct SovdLock {
    id: String,
}
// AI-generated - issue 7: end

struct CurrentModeController {
    http_client: reqwest::Client,
    powertrain_sovd_url: Url,
    // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 7
    powertrain_lock_url: Url,
    workload_api: WorkloadApiClient,
    authorization_policy: CompiledPolicy,
    // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
    status_publisher: Option<status::StatusPublisher>,
}

impl CurrentModeController {
    async fn new(cli: &Cli) -> Result<Self, Box<dyn std::error::Error>> {
        // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
        let mut http_client_builder = reqwest::Client::builder();
        if let Some(socket_path) = cli.get_sovd_server_unix_socket() {
            http_client_builder = http_client_builder.unix_socket(socket_path.as_path());
        }
        // AI-generated - issue 7: end
        Ok(Self {
            // AI-modified (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
            http_client: http_client_builder.build()?,
            powertrain_sovd_url: cli.get_sovd_powertrain_mode_resource_url()?,
            powertrain_lock_url: cli.get_sovd_powertrain_lock_resource_url()?,
            // AI-modified - issue 7: end
            workload_api: WorkloadApiClient::connect_env().await?,
            authorization_policy: cli.opa_config.get_compiled_auth_policy()?,
            // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
            status_publisher: cli
                .get_status_publisher_config()
                .map(status::StatusPublisher::start)
                .transpose()?,
        })
    }

    async fn authorize(
        &self,
        attributes: &UAttributes,
        method_id: u16,
    ) -> Result<JwtSvid, ServiceInvocationError> {
        let token = attributes.token().ok_or_else(|| {
            debug!("No token found in request attributes");
            ServiceInvocationError::Unauthenticated
        })?;
        let svid = self
            .workload_api
            .validate_jwt_token(AUDIENCE_POWERTRAIN_MODE_CONTROL, token)
            .await
            .map_err(|e| {
                debug!("Failed to validate JWT: {e}");
                ServiceInvocationError::Unauthenticated
            })?;
        debug!(
            "Successfully validated JWT provided by client [source: {}]",
            attributes.source_unchecked().to_uri(true)
        );

        let allowed = regorus::Value::from_yaml_str(&format!(
            r#"
            spiffe_id: "{}"
            method_id: {}
            "#,
            svid.spiffe_id(),
            method_id
        ))
        .and_then(|value| self.authorization_policy.eval_with_input(value))
        .map_err(|e| {
            debug!("Failed to authorize request using OPA: {e}");
            ServiceInvocationError::Internal(String::from("authorization error"))
        })?;
        if is_authorized(&allowed) {
            debug!(
                "Authorization successful for SPIFFE ID {} and method ID {}",
                svid.spiffe_id(),
                method_id
            );
            Ok(svid)
        } else {
            debug!(
                "Authorization failed for SPIFFE ID {} and method ID {}",
                svid.spiffe_id(),
                method_id
            );
            Err(ServiceInvocationError::PermissionDenied(String::from(
                "not authorized to invoke method",
            )))
        }
    }

    async fn fresh_svid(&self) -> Result<JwtSvid, ServiceInvocationError> {
        self.workload_api
            .fetch_jwt_svid(&[AUDIENCE_SOVD_CDA], None)
            .await
            .map_err(|e| {
                warn!("Error retrieving JWT SVID for accessing SOVD server: {e}");
                ServiceInvocationError::Unauthenticated
            })
    }

    // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
    async fn acquire_lock(&self, svid: &JwtSvid) -> Result<String, ServiceInvocationError> {
        let response = self
            .http_client
            .post(self.powertrain_lock_url.clone())
            .bearer_auth(svid.token())
            .json(&serde_json::json!({ "lock_expiration": SOVD_LOCK_EXPIRATION_SECS }))
            .send()
            .await
            .map_err(|e| {
                warn!("Error communicating with SOVD server: {e}");
                ServiceInvocationError::Unavailable("Cannot lock powertrain ECU".to_string())
            })?;
        if !response.status().is_success() {
            warn!(
                "Failed to lock powertrain ECU, SOVD server responded with status code {}",
                response.status()
            );
            return Err(ServiceInvocationError::Unavailable(
                "Cannot lock powertrain ECU".to_string(),
            ));
        }
        response
            .json::<SovdLock>()
            .await
            .map(|lock| {
                debug!("Acquired SOVD lock on powertrain ECU [id: {}]", lock.id);
                lock.id
            })
            .map_err(|e| {
                warn!("Error parsing lock response from SOVD server: {e}");
                ServiceInvocationError::Internal("internal error".to_string())
            })
    }

    async fn release_lock(&self, svid: &JwtSvid, lock_id: &str) {
        let mut lock_url = self.powertrain_lock_url.clone();
        if lock_url
            .path_segments_mut()
            .map(|mut segments| {
                segments.push(lock_id);
            })
            .is_err()
        {
            warn!("Cannot create URL for releasing SOVD lock [id: {lock_id}]");
            return;
        }
        match self
            .http_client
            .delete(lock_url)
            .bearer_auth(svid.token())
            .send()
            .await
        {
            Ok(response) if response.status().is_success() => {
                debug!("Released SOVD lock on powertrain ECU [id: {lock_id}]");
            }
            Ok(response) => warn!(
                "Failed to release SOVD lock [id: {lock_id}], SOVD server responded with status code {}",
                response.status()
            ),
            Err(e) => warn!("Error releasing SOVD lock [id: {lock_id}]: {e}"),
        }
    }
    // AI-generated - issue 7: end

    async fn get_current_mode(&self) -> Result<Option<UPayload>, ServiceInvocationError> {
        let svid = self.fresh_svid().await?;
        let response = self
            .http_client
            .get(self.powertrain_sovd_url.clone())
            .bearer_auth(svid.token())
            .send()
            .await
            .map_err(|e| {
                warn!("Error communicating with SOVD server: {e}");
                ServiceInvocationError::Unavailable("Cannot get current mode".to_string())
            })?;
        if !response.status().is_success() {
            Err(ServiceInvocationError::Unavailable(
                "Cannot get current mode".to_string(),
            ))
        } else {
            response
                .json::<Root>()
                .await
                .map(|root| root.data)
                .map_err(|e| {
                    warn!("Error parsing response from SOVD server: {e}");
                    ServiceInvocationError::Internal("internal error".to_string())
                })
                .and_then(|mode_message| {
                    serde_json::to_vec(&mode_message)
                        .map(|d| {
                            Some(UPayload::new(
                                d,
                                up_rust::UPayloadFormat::UPAYLOAD_FORMAT_JSON,
                            ))
                        })
                        .map_err(|e| {
                            warn!("Failed to serialize current mode response payload: {e}");
                            ServiceInvocationError::Internal(
                                "failed to serialize response".to_string(),
                            )
                        })
                })
        }
    }

    async fn set_current_mode(
        &self,
        request_payload: Option<UPayload>,
    ) -> Result<Option<UPayload>, ServiceInvocationError> {
        let svid = self.fresh_svid().await?;
        let mode_message = serde_json::from_slice::<ModeMessage>(
            &request_payload
                .ok_or_else(|| {
                    ServiceInvocationError::InvalidArgument("Request has no payload".to_string())
                })?
                .payload(),
        )
        .map_err(|e| {
            warn!("Failed to deserialize set mode request payload: {e}");
            ServiceInvocationError::InvalidArgument("Invalid payload".to_string())
        })?;
        let request_payload = Root {
            data: mode_message.clone(),
        };
        // AI-modified (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
        let lock_id = self.acquire_lock(&svid).await?;
        let result = self
            .http_client
            .put(self.powertrain_sovd_url.clone())
            .bearer_auth(svid.token())
            .json(&request_payload)
            .send()
            .await;
        self.release_lock(&svid, &lock_id).await;
        let response = result.map_err(|e| {
            warn!("Error communicating with SOVD server: {e}");
            ServiceInvocationError::Unavailable("Cannot set current mode".to_string())
        })?;
        // AI-modified - issue 7: end
        if !response.status().is_success() {
            warn!(
                "Failed to set powertrain mode, SOVD server responded with status code {}",
                response.status()
            );
            Err(ServiceInvocationError::Unavailable(
                "Cannot set current mode".to_string(),
            ))
        } else {
            info!("Powertrain mode set to: {:?}", mode_message.mode);
            // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
            if let Some(status_publisher) = &self.status_publisher {
                status_publisher.publish(mode_message);
            }
            Ok(None)
        }
    }
}

#[async_trait::async_trait]
impl RequestHandler for CurrentModeController {
    async fn handle_request(
        &self,
        resource_id: u16,
        message_attributes: &UAttributes,
        request_payload: Option<UPayload>,
    ) -> Result<Option<UPayload>, ServiceInvocationError> {
        let _svid = self.authorize(message_attributes, resource_id).await?;
        match resource_id {
            common::powertrain::RESOURCE_ID_GET_CURRENT_MODE => self.get_current_mode().await,
            common::powertrain::RESOURCE_ID_SET_CURRENT_MODE => {
                self.set_current_mode(request_payload).await
            }
            _ => Err(ServiceInvocationError::Unimplemented(
                "no such operation".to_string(),
            )),
        }
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    env_logger::init();
    let cli = cli::Cli::parse();
    let sovd_server_uri = cli.get_sovd_server_uri().to_owned();
    // AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 7: begin
    let sovd_server_unix_socket = cli
        .get_sovd_server_unix_socket()
        .map_or_else(|| String::from("none"), |p| p.display().to_string());
    // AI-generated - issue 7: end
    let mode_controller = CurrentModeController::new(&cli).await.map(Arc::new)?;

    let rpc_server = get_rpc_server(cli).await?;
    rpc_server
        .register_endpoint(
            None,
            common::powertrain::RESOURCE_ID_GET_CURRENT_MODE,
            mode_controller.clone(),
        )
        .await?;
    rpc_server
        .register_endpoint(
            None,
            common::powertrain::RESOURCE_ID_SET_CURRENT_MODE,
            mode_controller,
        )
        .await?;
    // AI-modified (GitHub Copilot, Claude Opus 5.5) - issue 7: log the Unix socket
    info!(
        "Powertrain mode control service is running [SOVD CDA Server: {}, Unix socket: {}]",
        sovd_server_uri, sovd_server_unix_socket
    );
    tokio::signal::ctrl_c().await?;
    info!("Powertrain mode control service is shutting down");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::is_authorized;
    use common::open_policy_agent::OpaConfig;
    use regorus::{CompiledPolicy, Value};

    const FMS: &str = "spiffe://sdv.eclipse.org/backend/fms";
    const VEHICLE_PROPERTIES: &str = "spiffe://sdv.eclipse.org/vehicle/properties";

    fn shipped_policy() -> CompiledPolicy {
        let config_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../config/powertrain-mode-controller");
        OpaConfig {
            policy_file: config_dir.join("authz.rego"),
            authorization_data_file: config_dir.join("authorization-data.json"),
            auth_rule_entrypoint: "data.authz.allow".to_string(),
        }
        .get_compiled_auth_policy()
        .expect("shipped authorization policy must compile")
    }

    fn evaluate(policy: &CompiledPolicy, input: serde_json::Value) -> Value {
        policy
            .eval_with_input(Value::from_json_str(&input.to_string()).unwrap())
            .expect("policy evaluation must succeed")
    }

    #[test]
    fn only_explicit_true_is_authorized() {
        assert!(is_authorized(&Value::Bool(true)));
        assert!(!is_authorized(&Value::Bool(false)));
        assert!(!is_authorized(&Value::Undefined));
        assert!(!is_authorized(&Value::Null));
        assert!(!is_authorized(&Value::from(1)));
        assert!(!is_authorized(&Value::from("true")));
    }

    #[test]
    fn shipped_policy_allows_configured_methods() {
        let policy = shipped_policy();
        for method_id in [1, 2] {
            let decision = evaluate(
                &policy,
                serde_json::json!({ "spiffe_id": FMS, "method_id": method_id }),
            );
            assert_eq!(decision, Value::Bool(true), "FMS method {method_id}");
            assert!(is_authorized(&decision));
        }
    }

    #[test]
    fn shipped_policy_explicitly_denies_unmatched_requests() {
        let policy = shipped_policy();
        let unmatched = [
            serde_json::json!({ "spiffe_id": VEHICLE_PROPERTIES, "method_id": 2 }),
            serde_json::json!({ "spiffe_id": "spiffe://sdv.eclipse.org/unknown", "method_id": 2 }),
            serde_json::json!({ "spiffe_id": FMS, "method_id": 3 }),
            serde_json::json!({ "spiffe_id": FMS }),
            serde_json::json!({ "method_id": 2 }),
            serde_json::json!({ "spiffe_id": FMS, "method_id": "2" }),
        ];
        for input in unmatched {
            let decision = evaluate(&policy, input.clone());
            assert_eq!(decision, Value::Bool(false), "input: {input}");
            assert!(!is_authorized(&decision), "input: {input}");
        }
    }
}
