# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# AI-generated (GitHub Copilot, Claude Opus 5.5) - i.MX95 two-board deployment
# installed as /etc/systemd/timesyncd.conf.d/sdv-imx95.conf

[Time]
NTP=192.168.2.101
FallbackNTP=
