# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# AI-generated (GitHub Copilot, Claude Opus 5.5) - i.MX95 Wi-Fi MQTT
# installed as /etc/systemd/network/20-mlan0.network.d/10-offline.conf
# local Wi-Fi subnet only: no internet route, and DNS/NTP stay as configured (time from the Mac)

[Network]
IPv6AcceptRA=no

[DHCPv4]
UseGateway=no
UseDNS=no
UseNTP=no
UseDomains=no
