# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# AI-generated (GitHub Copilot, Claude Opus 5.5) - i.MX95 two-board deployment
# installed as /etc/systemd/system/docker.service.d/10-wait-time-sync.conf
# SPIRE rejects certificates while the clock is wrong, so start containers after the first NTP sync

[Unit]
Wants=systemd-time-wait-sync.service
After=systemd-time-wait-sync.service time-sync.target
