# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
# SPDX-License-Identifier: Apache-2.0
# AI-generated (GitHub Copilot, Claude Opus 5.5) - i.MX95 two-board deployment
# installed as /etc/systemd/system/systemd-time-wait-sync.service.d/10-timeout.conf
# without the Mac, start Docker anyway (default is to wait forever)

[Service]
TimeoutStartSec=90
