#!/bin/bash

#*******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
#
# AI Disclosure: This file was largely AI-generated by GitHub Copilot
# (Claude Opus 5.5). The AI-generated portions may be considered public domain
# (CC0-1.0) and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.

#  Verifies that the SPIRE Workload API socket stays under exclusive control of
#  the SPIRE Agents.
#
#  Usage:
#    scripts/check_socket_hardening.sh [compose-file ...]
#        Static check of the Compose files. No containers are started.
#    scripts/check_socket_hardening.sh --runtime [--agent-restart]
#        Probes the running stack of the current Compose project (honours
#        COMPOSE_PROJECT_NAME, COMPOSE_FILE and COMPOSE_PROFILES) using
#        short-lived probe containers that borrow each workload's mounts and user.
#        --agent-restart additionally restarts each SPIRE Agent and verifies that
#        workloads reach the recreated socket without being restarted.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
readonly REPO_ROOT
readonly DEFAULT_COMPOSE_FILES=("$REPO_ROOT/docker-compose.yaml" "$REPO_ROOT/config/cda/docker-compose.yaml")
readonly PROBE_IMAGE=busybox:1.37
readonly AGENT_RESTART_TIMEOUT_SECS=60

CREATE_FILE_IN_DIR_PROBE=$(cat <<'SH'
probe="$1/.socket-hardening-probe-$$"
touch "$probe" 2>&1 && rm -f "$probe"
SH
)
readonly CREATE_FILE_IN_DIR_PROBE

SPIRE_PREDICATES_JQ=$(cat <<'JQ'
def is_spire_agent: (.image // "") | startswith("ghcr.io/spiffe/spire-agent");
def is_trusted_runtime_controller: is_spire_agent or .name == "dozzle";
def is_spire_workload_api_volume: .type == "volume" and (.source | test("^spire-agent(-[a-z]+)?-socket$"));
def is_container_runtime_socket: (.source // "") | test("/(docker|containerd|podman|crio)\\.sock$");
def workload_api_socket_path: (.environment.SPIFFE_ENDPOINT_SOCKET // "") | sub("^unix:"; "");
def is_spire_workload_api_client: (is_spire_agent | not) and (any(.volumes[]?; is_spire_workload_api_volume) or workload_api_socket_path != "");
def spire_workload_api_volume: first(.volumes[]? | select(is_spire_workload_api_volume) | .source) // "";
def mounts_workload_api_socket_directory: (workload_api_socket_path | sub("/[^/]+$"; "")) as $socket_dir | any(.volumes[]?; is_spire_workload_api_volume and .target == $socket_dir);
def runs_as_root: (.user // "") | test("^(|root|0)(:|$)");
def drops_all_capabilities: (.cap_drop // []) | index("ALL") != null;
def forbids_privilege_escalation: (.security_opt // []) | any(test("^no-new-privileges(:true)?$"));
def services: .services | to_entries[] | .value + {name: .key};
JQ
)
readonly SPIRE_PREDICATES_JQ

HARDENING_VIOLATIONS_JQ=$(cat <<'JQ'
services | . as $service
| (
    ( .volumes[]? | select(is_spire_workload_api_volume)
      | if ($service | is_spire_agent) then
          select(.read_only == true)
          | "\($service.name): SPIRE Agent needs a writable mount of \(.source) to manage its socket"
        else
          ( select(.read_only != true)
            | "\($service.name): mounts \(.source) writable, so it could replace the Agent socket" ),
          ( select(.volume.nocopy != true)
            | "\($service.name): mount of \(.source) lacks volume.nocopy, so its image could seed the volume" )
        end ),
    ( .volumes[]? | select(is_container_runtime_socket) | select($service | is_trusted_runtime_controller | not)
      | "\($service.name): mounts container runtime socket \(.source)" ),
    ( select(is_spire_workload_api_client)
      | ( select(runs_as_root) | "\(.name): Workload API client runs as root" ),
        ( select(drops_all_capabilities | not) | "\(.name): Workload API client does not drop ALL capabilities" ),
        ( select(forbids_privilege_escalation | not) | "\(.name): Workload API client allows privilege escalation (no-new-privileges missing)" ),
        ( select(mounts_workload_api_socket_directory | not)
          | "\(.name): SPIFFE_ENDPOINT_SOCKET \(workload_api_socket_path) is not inside a mounted SPIRE Agent socket volume directory, so it would not follow Agent restarts" ) )
  )
JQ
)
readonly HARDENING_VIOLATIONS_JQ

readonly WORKLOAD_API_CLIENTS_JQ='services | select(is_spire_workload_api_client) | [.name, spire_workload_api_volume, workload_api_socket_path] | @tsv'
readonly SPIRE_AGENTS_JQ='services | select(is_spire_agent) | [.name, spire_workload_api_volume, .image] | @tsv'

failures=0

require_command() {
  command -v "$1" >/dev/null || { echo "required command not found: $1" >&2; exit 2; }
}

spire_query() {
  jq -r "$SPIRE_PREDICATES_JQ $1"
}

pass() { echo "PASS $*"; }
fail() { echo "FAIL $*"; failures=$((failures + 1)); }

# ---- static check -----------------------------------------------------------

check_compose_files() {
  local compose_files=("$@")
  [[ ${#compose_files[@]} -gt 0 ]] || compose_files=("${DEFAULT_COMPOSE_FILES[@]}")

  local compose_file violations violation
  for compose_file in "${compose_files[@]}"; do
    violations=$(docker compose -f "$compose_file" --profile '*' config --format json | spire_query "$HARDENING_VIOLATIONS_JQ")
    if [[ -n "$violations" ]]; then
      fail "${compose_file#"$REPO_ROOT"/}"
      while IFS= read -r violation; do echo "  - $violation"; done <<< "$violations"
    else
      pass "${compose_file#"$REPO_ROOT"/}"
    fi
  done
}

# ---- runtime check ----------------------------------------------------------

running_container_of() {
  docker compose ps -q "$1"
}

workload_user() {
  local user
  user=$(docker inspect -f '{{.Config.User}}' "$1")
  echo "${user:-0:0}"
}

started_at() {
  docker inspect -f '{{.State.StartedAt}}' "$1"
}

run_with_mounts_and_user_of() {
  local container=$1; shift
  docker run --rm --network none --volumes-from "$container" --user "$(workload_user "$container")" "$@"
}

ensure_image() {
  docker image inspect "$1" >/dev/null 2>&1 || docker pull -q "$1" >/dev/null
}

can_reach_agent() {
  local container=$1 socket_path=$2 agent_image=$3
  run_with_mounts_and_user_of "$container" --entrypoint /opt/spire/bin/spire-agent "$agent_image" \
    healthcheck -socketPath "$socket_path" >/dev/null 2>&1
}

# Probes through the running container's own mount namespace: a fresh probe
# container would re-resolve the mount and hide a stale single-file mount.
can_reach_agent_through_live_mounts_of() {
  local container=$1 socket_path=$2 agent_image=$3 pid
  pid=$(docker inspect -f '{{.State.Pid}}' "$container")
  docker run --rm --pid=host --network none --cap-add SYS_PTRACE --entrypoint /opt/spire/bin/spire-agent "$agent_image" \
    healthcheck -socketPath "/proc/$pid/root$socket_path" >/dev/null 2>&1
}

socket_identity() {
  local container=$1 socket_path=$2
  run_with_mounts_and_user_of "$container" "$PROBE_IMAGE" stat -c 'inode=%i changed=%Z' "$socket_path"
}

check_socket_directory_is_read_only() {
  local service=$1 container=$2 socket_dir=$3 write_attempt
  if write_attempt=$(run_with_mounts_and_user_of "$container" "$PROBE_IMAGE" \
      sh -c "$CREATE_FILE_IN_DIR_PROBE" sh "$socket_dir"); then
    fail "$service: can create files in $socket_dir"
  elif [[ "$write_attempt" == *"Read-only file system"* ]]; then
    pass "$service: $socket_dir is mounted read-only"
  else
    fail "$service: $socket_dir is not mounted read-only (write only blocked by: ${write_attempt##*: })"
  fi
}

check_agent_is_reachable() {
  local service=$1 container=$2 socket_path=$3 agent_image=$4
  if can_reach_agent "$container" "$socket_path" "$agent_image"; then
    pass "$service: reaches the SPIRE Agent at $socket_path as user $(workload_user "$container")"
  else
    fail "$service: cannot reach the SPIRE Agent at $socket_path as user $(workload_user "$container")"
  fi
}

check_agent_restart_recovery() {
  local agent=$1 agent_volume=$2 agent_image=$3 clients=$4
  local service volume socket_path container first_container="" first_socket_path="" socket_before
  local client_start_times=""

  while IFS=$'\t' read -r service volume socket_path; do
    [[ "$volume" == "$agent_volume" ]] || continue
    container=$(running_container_of "$service")
    [[ -n "$first_container" ]] || { first_container=$container; first_socket_path=$socket_path; }
    client_start_times+="$service $(started_at "$container")"$'\n'
  done <<< "$clients"

  if [[ -z "$first_container" ]]; then
    echo "SKIP $agent: no running workload uses $agent_volume"
    return
  fi

  socket_before=$(socket_identity "$first_container" "$first_socket_path")
  docker compose restart "$agent" >/dev/null 2>&1

  local waited=0
  until can_reach_agent "$first_container" "$first_socket_path" "$agent_image"; do
    if (( waited >= AGENT_RESTART_TIMEOUT_SECS )); then
      fail "$agent: workloads cannot reach the socket within ${AGENT_RESTART_TIMEOUT_SECS}s after restart"
      return
    fi
    sleep 2; waited=$((waited + 2))
  done

  if [[ "$(socket_identity "$first_container" "$first_socket_path")" != "$socket_before" ]]; then
    pass "$agent: recreated its socket after restart"
  else
    fail "$agent: socket was not recreated after restart, so the recovery check is inconclusive"
  fi

  local start_time
  while IFS=$'\t' read -r service volume socket_path; do
    [[ "$volume" == "$agent_volume" ]] || continue
    container=$(running_container_of "$service")
    start_time=$(awk -v service="$service" '$1 == service { print $2 }' <<< "$client_start_times")
    if [[ "$(started_at "$container")" == "$start_time" ]] && can_reach_agent_through_live_mounts_of "$container" "$socket_path" "$agent_image"; then
      pass "$service: reaches the recreated $agent socket without being restarted"
    else
      fail "$service: did not recover from the $agent restart without being restarted"
    fi
  done <<< "$clients"
}

check_running_stack() {
  local restart_agents=$1
  local config clients agents agent_image
  config=$(docker compose config --format json)
  clients=$(spire_query "$WORKLOAD_API_CLIENTS_JQ" <<< "$config")
  agents=$(spire_query "$SPIRE_AGENTS_JQ" <<< "$config")
  agent_image=$(head -n1 <<< "$agents" | cut -f3)

  if [[ -z "$clients" || -z "$agent_image" ]]; then
    fail "no SPIRE Agent or Workload API client in the active Compose profiles"
    return
  fi
  ensure_image "$PROBE_IMAGE"
  ensure_image "$agent_image"

  local service volume socket_path container
  while IFS=$'\t' read -r service volume socket_path; do
    container=$(running_container_of "$service")
    if [[ -z "$container" ]]; then
      fail "$service: not running"
      continue
    fi
    check_socket_directory_is_read_only "$service" "$container" "$(dirname "$socket_path")"
    check_agent_is_reachable "$service" "$container" "$socket_path" "$agent_image"
  done <<< "$clients"

  if [[ "$restart_agents" == true ]]; then
    local agent agent_volume
    while IFS=$'\t' read -r agent agent_volume agent_image; do
      check_agent_restart_recovery "$agent" "$agent_volume" "$agent_image" "$clients"
    done <<< "$agents"
  fi
}

main() {
  require_command docker
  require_command jq

  local runtime=false restart_agents=false
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --runtime) runtime=true ;;
      --agent-restart) restart_agents=true ;;
      -*) echo "unknown option: $1" >&2; exit 2 ;;
      *) break ;;
    esac
    shift
  done

  if [[ "$runtime" == true ]]; then
    [[ $# -eq 0 ]] || { echo "--runtime checks the current Compose project; use COMPOSE_FILE instead of file arguments" >&2; exit 2; }
    check_running_stack "$restart_agents"
  else
    [[ "$restart_agents" == false ]] || { echo "--agent-restart requires --runtime" >&2; exit 2; }
    check_compose_files "$@"
  fi

  (( failures == 0 ))
}

main "$@"
