#!/bin/bash

#*******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
#
# AI Disclosure: This file was largely AI-generated by GitHub Copilot
# (Claude Opus 5.5). The AI-generated portions may be considered public domain
# (CC0-1.0) and not subject to the project's licence. The human contributor has
# reviewed and verified that the code is correct.

#  Statically verifies that the Compose files keep the SPIRE Workload API socket
#  under exclusive control of the SPIRE Agents. No containers are started.
#
#  Usage: scripts/check_socket_hardening.sh [compose-file ...]

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
readonly REPO_ROOT
readonly DEFAULT_COMPOSE_FILES=("$REPO_ROOT/docker-compose.yaml" "$REPO_ROOT/config/cda/docker-compose.yaml")

HARDENING_VIOLATIONS_JQ=$(cat <<'JQ'
def is_spire_agent: (.image // "") | startswith("ghcr.io/spiffe/spire-agent");
def is_trusted_runtime_controller: is_spire_agent or .name == "dozzle";
def is_spire_workload_api_volume: .type == "volume" and (.source | test("^spire-agent(-[a-z]+)?-socket$"));
def is_container_runtime_socket: (.source // "") | test("/(docker|containerd|podman|crio)\\.sock$");
def is_spire_workload_api_client: (is_spire_agent | not) and any(.volumes[]?; is_spire_workload_api_volume);
def runs_as_root: (.user // "") | test("^(|root|0)(:|$)");
def drops_all_capabilities: (.cap_drop // []) | index("ALL") != null;
def forbids_privilege_escalation: (.security_opt // []) | any(test("^no-new-privileges(:true)?$"));

.services | to_entries[] | .value + {name: .key} | . as $service
| (
    ( .volumes[]? | select(is_spire_workload_api_volume)
      | if ($service | is_spire_agent) then
          select(.read_only == true)
          | "\($service.name): SPIRE Agent needs a writable mount of \(.source) to manage its socket"
        else
          ( select(.read_only != true)
            | "\($service.name): mounts \(.source) writable, so it could replace the Agent socket" ),
          ( select(.volume.nocopy != true)
            | "\($service.name): mount of \(.source) lacks volume.nocopy, so its image could seed the volume" )
        end ),
    ( .volumes[]? | select(is_container_runtime_socket) | select($service | is_trusted_runtime_controller | not)
      | "\($service.name): mounts container runtime socket \(.source)" ),
    ( select(is_spire_workload_api_client)
      | ( select(runs_as_root) | "\(.name): Workload API client runs as root" ),
        ( select(drops_all_capabilities | not) | "\(.name): Workload API client does not drop ALL capabilities" ),
        ( select(forbids_privilege_escalation | not) | "\(.name): Workload API client allows privilege escalation (no-new-privileges missing)" ) )
  )
JQ
)
readonly HARDENING_VIOLATIONS_JQ

require_command() {
  command -v "$1" >/dev/null || { echo "required command not found: $1" >&2; exit 2; }
}

hardening_violations() {
  local compose_file=$1
  docker compose -f "$compose_file" --profile '*' config --format json | jq -r "$HARDENING_VIOLATIONS_JQ"
}

main() {
  require_command docker
  require_command jq

  local compose_files=("$@")
  [[ ${#compose_files[@]} -gt 0 ]] || compose_files=("${DEFAULT_COMPOSE_FILES[@]}")

  local compose_file violations violation failed=0
  for compose_file in "${compose_files[@]}"; do
    violations=$(hardening_violations "$compose_file")
    if [[ -n "$violations" ]]; then
      echo "FAIL ${compose_file#"$REPO_ROOT"/}"
      while IFS= read -r violation; do echo "  - $violation"; done <<< "$violations"
      failed=1
    else
      echo "PASS ${compose_file#"$REPO_ROOT"/}"
    fi
  done
  return "$failed"
}

main "$@"
