#!/bin/bash

#*******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#*******************************************************************************
#
#  This script was generated with the help of AI

#  Approves the locally built workload images and registers them with the
#  SPIRE server.
#
#  Generating the approved-workloads.yaml here simulates the step an OEM's
#  release pipeline would perform (and sign) at image release time. The
#  registration below then consumes that list, mirroring how a deployment
#  host would enforce a pipeline-provided allowlist in production.

set -euo pipefail

APPROVED_FILE="$(dirname "$0")/../config/spire/approved-workloads.yaml"

#  The workload inventory: SPIFFE ID, image, and compose service name.
#  The zone (vehicle/backend) in the SPIFFE ID selects the SPIRE agent.
WORKLOADS=(
  "spiffe://sdv.eclipse.org/vehicle/powertrain-mode-controller ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/powertrain-mode-controller:latest powertrain-mode-controller"
  "spiffe://sdv.eclipse.org/vehicle/properties                 ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/vehicle-properties:latest         vehicle-properties"
  "spiffe://sdv.eclipse.org/backend/fms                        ghcr.io/eclipse-sdv-blueprints/commercial-sdv-stack/fms:latest                        fms"
)

#  Helper to access spire server functions
spire_server() {
  # -T + </dev/null: keep docker exec from consuming the loop's stdin
  docker compose exec -T spire-server \
    /opt/spire/bin/spire-server "$@" \
      -socketPath /run/spire/server/private/api.sock </dev/null
}

#  Generate the approved workloads list from the locally built images
{
  echo "# GENERATED by scripts/register_workloads.sh - DO NOT EDIT"
  echo "# In production this file would be produced and signed by the OEM's"
  echo "# release pipeline at image release time; generating it here simulates"
  echo "# that approval step for the blueprint."
  echo "workloads:"
} > "$APPROVED_FILE"

for workload in "${WORKLOADS[@]}"; do
  read -r spiffe_id image service <<< "$workload"
  if ! digest=$(docker image inspect -f '{{.Id}}' "$image" 2>/dev/null); then
    echo "image not built locally: $image (build it with: docker compose build $service)" >&2
    exit 1
  fi
  # AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16: Podman prints image IDs without
  # the algorithm prefix that SPIRE's selectors use
  case "$digest" in sha256:*) ;; *) digest="sha256:$digest" ;; esac
  echo "approving $spiffe_id -> $digest"
  {
    printf '  - spiffe_id: "%s"\n' "$spiffe_id"
    printf '    image_config_digest: "%s"\n' "$digest"
    printf '    compose_service: "%s"\n' "$service"
  } >> "$APPROVED_FILE"
done

#  Remove existing registrations
#  For the purpose of demo/blueprint this is fine
spire_server entry show | awk '/^Entry ID/ {print $4}' | while read -r id; do
  echo "deleting entry $id"
  spire_server entry delete -entryID "$id" >/dev/null
done

#  Flatten the approved workloads YAML into "spiffe_id digest service" lines.
#  Only the simple structure written above is supported (no yq dependency).
parse_approved() {
  awk '
    function val(s) { sub(/^[^:]*:[ \t]*/, "", s); gsub(/^"|"$/, "", s); return s }
    /^[ \t]*#/ { next }
    /^[ \t]*-?[ \t]*spiffe_id:/           { id = val($0) }
    /^[ \t]*-?[ \t]*image_config_digest:/ { dg = val($0) }
    /^[ \t]*-?[ \t]*compose_service:/     { sv = val($0) }
    id != "" && dg != "" && sv != ""      { print id, dg, sv; id = dg = sv = "" }
  ' "$1"
}

#  Register the approved workloads with the SPIRE server
while read -r -u 3 spiffe_id digest service; do
  zone=$(echo "$spiffe_id" | cut -d/ -f4)
  case "$zone" in
    backend) agent=spire-agent-backend ;;
    vehicle) agent=spire-agent-vehicle ;;
    *) echo "unknown zone '$zone' in $spiffe_id" >&2; exit 1 ;;
  esac

  echo "registering $spiffe_id"
  spire_server entry create \
    -parentID "spiffe://sdv.eclipse.org/spire/agent/x509pop/${agent}" \
    -spiffeID "$spiffe_id" \
    -selector "docker:image_config_digest:${digest}" >/dev/null

  # warn if the running container was started from a different image than the
  # one just approved - it will be denied an SVID until it is recreated
  container=$(docker compose ps -q "$service" 2>/dev/null || true)
  if [[ -n "$container" ]]; then
    running=$(docker inspect -f '{{.Image}}' "$container")
    # AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16
    case "$running" in sha256:*) ;; *) running="sha256:$running" ;; esac
    if [[ "$running" != "$digest" ]]; then
      echo "WARNING: running '$service' container uses image $running," >&2
      echo "         which does not match the approved digest - it will be denied" >&2
      echo "         an SVID until recreated (docker compose up -d $service)" >&2
    fi
  fi
done 3< <(parse_approved "$APPROVED_FILE")
