#
# SPDX-FileCopyrightText: Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
#
# AI-generated (GitHub Copilot, Claude Opus 5.5) - issue 16

[package]
name = "anomaly-detector"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true, default-features = false, features = [
    "std",
    "derive",
    "env",
    "color",
    "help",
    "usage",
    "error-context",
    "suggestions",
] }
env_logger = { workspace = true }
humantime = { version = "2.4.0" }
log = { workspace = true }
# same version and features as used by up-transport-mqtt5
paho-mqtt = { version = "0.13.3", features = ["vendored-ssl"] }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal", "sync", "time"] }
